### PR TITLE
Fix isEmpty calculations, add property to collection models

### LINKED ISSUE #48: Fix table empty state + add isEmpty to collection section model
EDIT: `isEmpty` should check *all* sections

Empty tables have 1 section model with no cell models and nil header/footer models. Section models should be empty in this case. 

```bash
  ▿ 0 : SectionModel
    ▿ cellViewModels : Optional<Array<FluxTableViewCellViewModel>>
      - some : 0 elements
    ▿ headerViewModel : Optional<FluxTableViewSectionHeaderFooterViewModel>
      ▿ some : (PlainHeaderFooterViewModel in _BEA0F9974F0956F35FD050A4BA315CE5)
        - title : nil
        - height : nil
        - viewInfo : nil
    ▿ footerViewModel : Optional<FluxTableViewSectionHeaderFooterViewModel>
      ▿ some : (PlainHeaderFooterViewModel in _BEA0F9974F0956F35FD050A4BA315CE5)
        - title : nil
        ▿ height : Optional<CGFloat>
          - some : 0.0
        - viewInfo : nil
    - collapsed : false
    - diffingKey : nil
```

### PR DESCRIPTION
**Pull request by jessesquires**
- Fix `TableViewModel.isEmpty` calculation
- Add `CollectionSectionViewModel.isEmpty`
- Add `CollectionViewModel.isEmpty`
- Remove undocumented initializers for `CollectionSectionViewModel` (the ones that received `headerHeight:` and/or `footerHeight:`)
These were causing ambiguous naming errors. Also, we don't use them in PlanGrid.

Closes #48

### CODE REVIEW

File: Sources/CollectionViewModel.swift [hunk 1]
```diff
@@ -155,59 +166,4 @@ public struct CollectionSectionViewModel: DiffableViewModel {
...
-        cellViewModels: [CollectionCellViewModel],
-        headerHeight: CGFloat? = nil,
-        footerHeight: CGFloat? = nil,
-        diffingKey: String = UUID().uuidString) {
-        self.init(
-            cellViewModels: cellViewModels,
-            headerViewModel: BlankSupplementaryViewModel(height: headerHeight),
-            footerViewModel: BlankSupplementaryViewModel(height: footerHeight),
-            diffingKey: diffingKey)
-    }
```
Comment (jessesquires) [inline Sources/CollectionViewModel.swift]: These were causing ambiguous naming errors in Swift (probably because of my diffing key changes)

Per the comment above, these needed to be removed anyway. 

We don't use them in PlanGrid either, so 👌
