### PR TITLE
Dwifft -> DifferenceKit

### LINKED ISSUE #126: [Crash] Auto-diffing bugs and crashes
Diffing for collection views with multiple sections fails. And possibly other scenarios.

We don't use this in PlanGrid, so we aren't currently affected by this.

Seems to be a bug in `Dwifft`. Switching to `IGListKit/Diffing` is now a top priority.

See also: #125

Currently had to disable this test:
https://github.com/plangrid/ReactiveLists/blob/master/Tests/CollectionView/CollectionViewDriverDiffingTests.swift#L78

## Repro steps

For both table and collection views:

1. Launch example app
1. Delete all items from first section
1. Tap "Flip" button to swap sections until you crash

### PR DESCRIPTION
**Pull request by benasher44**
## Changes in this pull request

This swaps out Dwifft for DifferenceKit, which uses Paul Heckel's more efficient diffing algo (same one used by IGListKit). Most of the work here is adding layers to avoid `Self`/`associatedtype` requirements issues with our protocols. These layers could be removed in the future though, pending changes that would allow this in Swift 5 or generics changes to `TableViewModel`/`CollectionViewModel`.

This also fixes #126 

### Checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I added tests, an experiment, or detailed why my change isn't tested.
- [x] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [x] I have reviewed the [contributing guide](https://github.com/plangrid/ReactiveLists/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by benasher44** [comment]
Preliminary tests using this with problem projects in PG look really good. Going to hold off putting in more effort here, until we can do more thorough testing internally.

File: Sources/Diffing.swift [hunk 1]
```diff
@@ -40,3 +41,118 @@ public extension DiffableViewModel {
         return String(describing: Self.self)
     }
 }
+
+/// MARK: - DifferenceKit Helpers
+
+/// Creates a type-erased Differentiable for DiffableViewModel.
+/// These are only created internally from either `TableCellViewModel` or `CollectionCellViewModel`,
+/// so that we can safely force cast the models back to those types.
+public struct AnyDiffableViewModel {
```
Comment (benasher44) [inline Sources/Diffing.swift]: Can some of these helper types be made non-public?

Comment (benasher44) [reply Sources/Diffing.swift]: Nope. They're used in public methods/vars that are requirements of public protocols.

File: Sources/CollectionViewDriver.swift [hunk 2]
```diff
@@ -128,46 +130,51 @@ public class CollectionViewDriver: NSObject {
...
+            let changeset = StagedChangeset(source: old, target: newModel.sectionModels)
+            if changeset.isEmpty {
+                self._collectionViewModel = newModel
             } else {
-                self.refreshViews()
+                self.collectionView.reload(using: changeset) {
+                    self._collectionViewModel = CollectionViewModel(sectionModels: $0)
+                }
             }
+            self.refreshViews()
```
Comment (jessesquires) [inline Sources/CollectionViewDriver.swift]: 👌 Looks much cleaner

File: Sources/Diffing.swift (hunk 1 above)
Comment (jessesquires) [reply Sources/Diffing.swift]: If this struct is only used internally, can it be `internal` instead of `public`? 

Maybe I'm misreading your comment?

File: Sources/Diffing.swift [hunk 3]
```diff
@@ -40,3 +41,118 @@ public extension DiffableViewModel {
...
+        let sectionModel = model.model
+        self.init(
+            //swiftlint:disable:next force_cast
+            cellViewModels: elements.map { $0.model as! CollectionCellViewModel },
+            headerViewModel: sectionModel.headerViewModel,
+            footerViewModel: sectionModel.footerViewModel,
+            diffingKey: sectionModel.diffingKey
+        )
+    }
+}
```
Comment (jessesquires) [inline Sources/Diffing.swift]: 🎉

File: Sources/Diffing.swift (hunk 1 above)
Comment (benasher44) [reply Sources/Diffing.swift]: `AnyDiffableViewModel` is used in a decl that satisfies a protocol for a public type, so this has to be public.

Comment (jessesquires) [reply Sources/Diffing.swift]: Ah, got it 👍

File: Sources/Diffing.swift [hunk 4]
```diff
@@ -40,3 +41,118 @@ public extension DiffableViewModel {
...
+    }
+
+    public func isContentEqual(to source: DifferentiableSectionModel) -> Bool {
+        return self.isContentEqualTo(source)
+    }
+}
+
+/// MARK: - DifferenceKit Protocol Conformance
+
+extension TableSectionViewModel: DifferentiableSection {
```
Comment (benasher44) [inline Sources/Diffing.swift]: @jessesquires `AnyDiffableViewModel` is used to satisfy the `DifferentiableSection` protocol. Because `TableSectionViewModel` is `public`, this protocol implementation must be made public (and cascades back to `AnyDiffableViewModel`)

Comment (jessesquires) [reply Sources/Diffing.swift]: Ah, got it 👍

**Comment by jessesquires** [comment]
I'm assuming this fixes #126 ?

**Comment by benasher44** [comment]
@jessesquires possibly? TBH, I can't tell what should be broken about UICollectionView diffing. AFAICT, the test issue I fixed in #131 was a test-only problem.

**Comment by benasher44** [comment]
@jessesquires this is ready for final review! I think we're happy with internal testing cc @sasilukr

**Comment by benasher44** [comment]
@jessesquires oh wait no this still needs tests and changelog entry. will update again once that's done.

**Comment by benasher44** [comment]
@jessesquires `DifferenceKit` properly checks for the presence of the view's `window` before attempting to perform animated updates, which breaks tests (e.g. means reload data gets called instead of calls to delete sections). Some options:

1. Delete tests that test the "what is the difference," since we have relegated the responsibility of diffing to a library and therefore falls out of scope of our testing. Instead, we could test "did we attempt to diff as opposed to not diffing".
2. Figure out how to get a window involved in our tests

Thoughts?

**Comment by jessesquires** [comment]
@benasher44 Either approach sounds reasonable. You can add the table/collection views to a UIWindow in the tests (I'm pretty sure). 

But, I'm leaning toward (1) — seems like we shouldn't be writing tests for the actual diffing lib.

**Comment by benasher44** [comment]
I think best way forward to fixing tests is leveraging protocol-based mocking. I've started with a PR for DifferenceKit: ra1028/DifferenceKit#27

**Comment by benasher44** [comment]
@jessesquires adding the window, properly overriding performBatchUpdates, and remove some super calls gets tests to pass. This is ready for final approval!

Also, confirmed #126 is fixed.

**Comment by benasher44** [comment]
Travis appears to be failing because their specs are out of date.

**Comment by PlanBot-iOS** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by benasher44** [comment]
Add `pod repo update` as a `before_install` step.

File: Sources/Diffing.swift [hunk 5]
```diff
@@ -40,3 +41,104 @@ public extension DiffableViewModel {
...
+public struct AnyDiffableViewModel {
+    public let model: DiffableViewModel
+
+    private let isContentEqualTo: (AnyDiffableViewModel) -> Bool
+
+    init(_ model: TableCellViewModel) {
+        self.model = model
+
+        let differenceIdentifier = model.diffingKey
+        /// Only compares diff identifiers. This means we'll never get "reload"-type `Changeset`s
```
Comment (jessesquires) [inline Sources/Diffing.swift]: hm... isn't this a problem? what if a cell updates it's content and needs to be refreshed? (but it's diff identifier wouldn't change...)

Comment (benasher44) [reply Sources/Diffing.swift]: We do it manually for the cells on screen in ReactiveLists, which is how it works today.

Comment (benasher44) [reply Sources/Diffing.swift]: We could revisit this in the future to see if this is something we want to support (using diffing to animate reloading of cells), but right now it would break forms (e.g. jumping fields because of keyboard dismissal)

Comment (jessesquires) [reply Sources/Diffing.swift]: ah, right 👍 sounds good to me
